---
name: Build and sign image
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_and_sign_image:
    name: Build and sign image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build EIF
        id: build-eif
        uses: richardfan1126/nitro-enclaves-eif-build-action@dev
        with:
          docker-build-context-path: enclave
          enable-ghcr-push: true
          enable-artifact-sign: true
          eif-file-name: enclave.eif
          eif-info-file-name: enclave-info.json
          artifact-tag: ${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print outputs
        env:
          EIF_FILE_PATH: ${{ steps.build-eif.outputs.eif-file-path }}
          EIF_INFO_PATH: ${{ steps.build-eif.outputs.eif-info-path }}
          GHCR_ARTIFACT_DIGEST: ${{ steps.build-eif.outputs.ghcr-artifact-digest }}
          GHCR_ARTIFACT_PATH: ${{ steps.build-eif.outputs.ghcr-artifact-path }}
          REKOR_LOG_INDEX: ${{ steps.build-eif.outputs.rekor-log-index }}
        run: |
          echo "${EIF_FILE_PATH}"
          echo "${EIF_INFO_PATH}"
          echo "${GHCR_ARTIFACT_DIGEST}"
          echo "${GHCR_ARTIFACT_PATH}"
          echo "${REKOR_LOG_INDEX}"
