---
name: Build and sign image
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_eif_file:
    name: Build EIF file
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build image
        shell: bash
        run: |
          cd ${{ github.workspace }}/enclave
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Check install!
        shell: bash
        run: cosign version
      
      - name: Log into ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        shell: bash
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
